// Generated by CoffeeScript 1.6.3
(function() {
  describe("version", function() {
    return it("is set", function() {
      var ramsey;
      ramsey = new Ramsey();
      return expect(ramsey.version).toBe("0.0.1");
    });
  });

  describe("scope inspector", function() {
    var ramsey;
    ramsey = null;
    beforeEach(function() {
      return ramsey = new Ramsey();
    });
    afterEach(function() {
      return delete window.foo;
    });
    it("can detect a clean global scope", function() {
      return expect(Object.keys(ramsey.globalPollution)).toEqual([]);
    });
    return it("can detect a dirty global scope", function() {
      window.foo = 'bar';
      return expect(Object.keys(ramsey.globalPollution)).toEqual(['foo']);
    });
  });

  describe("");

}).call(this);
